root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
stop_grace_period: 0
wal_rotate_interval: 5
stale_threshold: 5
bgworkers:
  - module: tradingviewfeeder.so
    config:
      base_timeframe: "1Min"
      bars: 128
      symbols:
        BYBIT:
          - BTCUSDT
          - BTCUSDT.P
          - ETHUSDT
          - ETHUSDT.P
        BINANCE:
          - BTCUSDT
          - BTCUSDT.P
          - ETHUSDT
          - ETHUSDT.P
        TVC:
          - US02Y
          - US10Y
          - USOIL
          - VIX
          - GOLD
        FXCM:
          - SPX500
          - US30
          - USDJPY
          - EURUSD
triggers:
  - module: stream.so
    on: "*/*/*"
    config:
      filter: ""
